name: Nezha Dashboard and Agent Monitor

on:
  schedule:
    # 每隔5分钟运行一次，可以根据需要调整时间
    - cron: '*/5 * * * *'

jobs:
  check-nezha-processes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Check and restart Nezha dashboard and agent processes
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
        pgrep -f 'dashboard' | xargs -r kill
        pgrep -f 'nezha-agent' | xargs -r kill
        cd /home/zzzxxx/.nezha-dashboard
        nohup /home/zzzxxx/.nezha-dashboard/start.sh >/dev/null 2>&1 &
        cd /home/zzzxxx/.nezha-agent
        nohup /home/zzzxxx/.nezha-agent/start.sh >/dev/null 2>&1 &"
